<?php

namespace Database\Seeders;

use App\Models\SeoSetting;
use Illuminate\Database\Seeder;

class SeoSettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // ── SEO Title ─────────────────────────────────
            [
                'key' => 'seo_title_min_length',
                'label' => 'SEO Title - Panjang Minimum',
                'description' => 'Panjang minimum judul SEO dalam karakter',
                'group' => 'title',
                'type' => 'integer',
                'value' => '55',
                'default_value' => '55',
                'unit' => 'karakter',
                'sort_order' => 1,
            ],
            [
                'key' => 'seo_title_max_length',
                'label' => 'SEO Title - Panjang Maksimum',
                'description' => 'Panjang maksimum judul SEO. Jika terlalu panjang, Google memotong judul.',
                'group' => 'title',
                'type' => 'integer',
                'value' => '65',
                'default_value' => '65',
                'unit' => 'karakter',
                'sort_order' => 2,
            ],
            [
                'key' => 'seo_title_ideal_max',
                'label' => 'SEO Title - Panjang Ideal Maks',
                'description' => 'Panjang ideal untuk judul SEO',
                'group' => 'title',
                'type' => 'integer',
                'value' => '60',
                'default_value' => '60',
                'unit' => 'karakter',
                'sort_order' => 3,
            ],
            [
                'key' => 'seo_title_keyword_at_start',
                'label' => 'SEO Title - Keyword di Awal',
                'description' => 'Keyword harus muncul di awal judul',
                'group' => 'title',
                'type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'unit' => null,
                'sort_order' => 4,
            ],

            // ── H1 Heading ─────────────────────────────────
            [
                'key' => 'h1_min_length',
                'label' => 'H1 - Panjang Minimum',
                'description' => 'Panjang minimum H1 (judul artikel)',
                'group' => 'title',
                'type' => 'integer',
                'value' => '60',
                'default_value' => '60',
                'unit' => 'karakter',
                'sort_order' => 5,
            ],
            [
                'key' => 'h1_max_length',
                'label' => 'H1 - Panjang Maksimum',
                'description' => 'Panjang maksimum H1 (boleh lebih panjang dari SEO title)',
                'group' => 'title',
                'type' => 'integer',
                'value' => '80',
                'default_value' => '80',
                'unit' => 'karakter',
                'sort_order' => 6,
            ],

            // ── URL / Slug ─────────────────────────────────
            [
                'key' => 'slug_max_words',
                'label' => 'Slug - Jumlah Kata Maksimal',
                'description' => 'Slug harus pendek dan hanya berisi keyword utama',
                'group' => 'meta',
                'type' => 'integer',
                'value' => '5',
                'default_value' => '5',
                'unit' => 'kata',
                'sort_order' => 10,
            ],

            // ── Meta Description ─────────────────────────────────
            [
                'key' => 'meta_desc_min_length',
                'label' => 'Meta Description - Panjang Minimum',
                'description' => 'Panjang minimum meta description',
                'group' => 'meta',
                'type' => 'integer',
                'value' => '140',
                'default_value' => '140',
                'unit' => 'karakter',
                'sort_order' => 11,
            ],
            [
                'key' => 'meta_desc_max_length',
                'label' => 'Meta Description - Panjang Maksimum',
                'description' => 'Panjang maksimum meta description',
                'group' => 'meta',
                'type' => 'integer',
                'value' => '160',
                'default_value' => '160',
                'unit' => 'karakter',
                'sort_order' => 12,
            ],
            [
                'key' => 'meta_desc_ideal_max',
                'label' => 'Meta Description - Panjang Ideal Maks',
                'description' => 'Panjang ideal terbaik untuk meta description',
                'group' => 'meta',
                'type' => 'integer',
                'value' => '155',
                'default_value' => '155',
                'unit' => 'karakter',
                'sort_order' => 13,
            ],

            // ── Intro / Paragraf Pembuka ─────────────────────────────────
            [
                'key' => 'intro_min_words',
                'label' => 'Paragraf Pembuka - Kata Minimum',
                'description' => 'Jumlah minimal kata di paragraf pertama. AI & Google sering mengambilnya sebagai ringkasan.',
                'group' => 'content',
                'type' => 'integer',
                'value' => '80',
                'default_value' => '80',
                'unit' => 'kata',
                'sort_order' => 20,
            ],
            [
                'key' => 'intro_max_words',
                'label' => 'Paragraf Pembuka - Kata Maksimum',
                'description' => 'Jumlah maksimal kata di paragraf pertama',
                'group' => 'content',
                'type' => 'integer',
                'value' => '120',
                'default_value' => '120',
                'unit' => 'kata',
                'sort_order' => 21,
            ],
            [
                'key' => 'intro_keyword_within_words',
                'label' => 'Keyword di Intro - Dalam N Kata Pertama',
                'description' => 'Keyword harus muncul dalam N kata pertama artikel',
                'group' => 'content',
                'type' => 'integer',
                'value' => '50',
                'default_value' => '50',
                'unit' => 'kata',
                'sort_order' => 22,
            ],

            // ── Panjang Artikel ─────────────────────────────────
            [
                'key' => 'article_min_words',
                'label' => 'Panjang Artikel - Minimum',
                'description' => 'Jumlah kata minimum artikel. Penting untuk topical authority.',
                'group' => 'content',
                'type' => 'integer',
                'value' => '1800',
                'default_value' => '1800',
                'unit' => 'kata',
                'sort_order' => 23,
            ],
            [
                'key' => 'article_ideal_words',
                'label' => 'Panjang Artikel - Ideal',
                'description' => 'Jumlah kata ideal untuk ranking kompetitif',
                'group' => 'content',
                'type' => 'integer',
                'value' => '2000',
                'default_value' => '2000',
                'unit' => 'kata',
                'sort_order' => 24,
            ],
            [
                'key' => 'article_max_ideal_words',
                'label' => 'Panjang Artikel - Ideal Maks',
                'description' => 'Batas atas jumlah kata ideal',
                'group' => 'content',
                'type' => 'integer',
                'value' => '2500',
                'default_value' => '2500',
                'unit' => 'kata',
                'sort_order' => 25,
            ],

            // ── Paragraf & Readability ─────────────────────────────────
            [
                'key' => 'paragraph_min_sentences',
                'label' => 'Paragraf - Kalimat Minimum',
                'description' => 'Jumlah kalimat minimum per paragraf',
                'group' => 'content',
                'type' => 'integer',
                'value' => '2',
                'default_value' => '2',
                'unit' => 'kalimat',
                'sort_order' => 26,
            ],
            [
                'key' => 'paragraph_max_sentences',
                'label' => 'Paragraf - Kalimat Maksimum',
                'description' => 'Jumlah kalimat maksimum per paragraf untuk readability',
                'group' => 'content',
                'type' => 'integer',
                'value' => '4',
                'default_value' => '4',
                'unit' => 'kalimat',
                'sort_order' => 27,
            ],
            [
                'key' => 'sentence_min_words',
                'label' => 'Kalimat - Kata Minimum',
                'description' => 'Panjang minimal kata per kalimat',
                'group' => 'content',
                'type' => 'integer',
                'value' => '12',
                'default_value' => '12',
                'unit' => 'kata',
                'sort_order' => 28,
            ],
            [
                'key' => 'sentence_max_words',
                'label' => 'Kalimat - Kata Maksimum',
                'description' => 'Panjang maksimal kata per kalimat',
                'group' => 'content',
                'type' => 'integer',
                'value' => '20',
                'default_value' => '20',
                'unit' => 'kata',
                'sort_order' => 29,
            ],

            // ── Heading Structure ─────────────────────────────────
            [
                'key' => 'h2_min_count',
                'label' => 'H2 - Jumlah Minimum',
                'description' => 'Jumlah minimum heading H2 dalam artikel',
                'group' => 'structure',
                'type' => 'integer',
                'value' => '5',
                'default_value' => '5',
                'unit' => 'buah',
                'sort_order' => 30,
            ],
            [
                'key' => 'h2_max_count',
                'label' => 'H2 - Jumlah Maksimum',
                'description' => 'Jumlah maksimum heading H2',
                'group' => 'structure',
                'type' => 'integer',
                'value' => '8',
                'default_value' => '8',
                'unit' => 'buah',
                'sort_order' => 31,
            ],
            [
                'key' => 'h3_min_count',
                'label' => 'H3 - Jumlah Minimum',
                'description' => 'Jumlah minimum heading H3',
                'group' => 'structure',
                'type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'unit' => 'buah',
                'sort_order' => 32,
            ],
            [
                'key' => 'h3_max_count',
                'label' => 'H3 - Jumlah Maksimum',
                'description' => 'Jumlah maksimum heading H3',
                'group' => 'structure',
                'type' => 'integer',
                'value' => '6',
                'default_value' => '6',
                'unit' => 'buah',
                'sort_order' => 33,
            ],
            [
                'key' => 'min_bullet_sections',
                'label' => 'Bullet/List Section - Minimum',
                'description' => 'Jumlah minimal section yang menggunakan list/bullet. Membantu readability dan AI parsing.',
                'group' => 'structure',
                'type' => 'integer',
                'value' => '2',
                'default_value' => '2',
                'unit' => 'section',
                'sort_order' => 34,
            ],

            // ── Keyword Density ─────────────────────────────────
            [
                'key' => 'keyword_density_min',
                'label' => 'Keyword Density - Minimum',
                'description' => 'Persentase minimum kepadatan keyword utama',
                'group' => 'keyword',
                'type' => 'float',
                'value' => '1.0',
                'default_value' => '1.0',
                'unit' => '%',
                'sort_order' => 40,
            ],
            [
                'key' => 'keyword_density_max',
                'label' => 'Keyword Density - Maksimum',
                'description' => 'Persentase maksimum kepadatan keyword utama',
                'group' => 'keyword',
                'type' => 'float',
                'value' => '1.5',
                'default_value' => '1.5',
                'unit' => '%',
                'sort_order' => 41,
            ],
            [
                'key' => 'keyword_min_occurrences',
                'label' => 'Keyword - Kemunculan Minimum',
                'description' => 'Jumlah minimum kemunculan keyword utama (untuk artikel ~2000 kata)',
                'group' => 'keyword',
                'type' => 'integer',
                'value' => '20',
                'default_value' => '20',
                'unit' => 'kali',
                'sort_order' => 42,
            ],
            [
                'key' => 'keyword_max_occurrences',
                'label' => 'Keyword - Kemunculan Maksimum',
                'description' => 'Jumlah maksimum kemunculan keyword utama',
                'group' => 'keyword',
                'type' => 'integer',
                'value' => '30',
                'default_value' => '30',
                'unit' => 'kali',
                'sort_order' => 43,
            ],
            [
                'key' => 'lsi_keyword_min',
                'label' => 'LSI Keyword - Variasi Minimum',
                'description' => 'Jumlah minimum variasi keyword (LSI keyword) yang harus muncul',
                'group' => 'keyword',
                'type' => 'integer',
                'value' => '5',
                'default_value' => '5',
                'unit' => 'variasi',
                'sort_order' => 44,
            ],
            [
                'key' => 'lsi_keyword_max',
                'label' => 'LSI Keyword - Variasi Maksimum',
                'description' => 'Jumlah ideal variasi keyword yang optimal',
                'group' => 'keyword',
                'type' => 'integer',
                'value' => '10',
                'default_value' => '10',
                'unit' => 'variasi',
                'sort_order' => 45,
            ],
            [
                'key' => 'keyword_in_conclusion',
                'label' => 'Keyword di Kesimpulan',
                'description' => 'Keyword wajib muncul di paragraf penutup / kesimpulan',
                'group' => 'keyword',
                'type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'unit' => null,
                'sort_order' => 46,
            ],

            // ── Internal & External Links ─────────────────────────────────
            [
                'key' => 'internal_link_min',
                'label' => 'Internal Link - Minimum',
                'description' => 'Jumlah minimun internal link untuk SEO dan topical authority',
                'group' => 'links',
                'type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'unit' => 'link',
                'sort_order' => 50,
            ],
            [
                'key' => 'internal_link_ideal',
                'label' => 'Internal Link - Ideal',
                'description' => 'Jumlah ideal internal link',
                'group' => 'links',
                'type' => 'integer',
                'value' => '5',
                'default_value' => '5',
                'unit' => 'link',
                'sort_order' => 51,
            ],
            [
                'key' => 'external_link_min',
                'label' => 'External Link - Minimum',
                'description' => 'Jumlah minimum external link untuk kredibilitas',
                'group' => 'links',
                'type' => 'integer',
                'value' => '1',
                'default_value' => '1',
                'unit' => 'link',
                'sort_order' => 52,
            ],
            [
                'key' => 'external_link_ideal',
                'label' => 'External Link - Ideal',
                'description' => 'Jumlah ideal external link',
                'group' => 'links',
                'type' => 'integer',
                'value' => '2',
                'default_value' => '2',
                'unit' => 'link',
                'sort_order' => 53,
            ],

            // ── Image ─────────────────────────────────
            [
                'key' => 'image_min_count',
                'label' => 'Gambar - Jumlah Minimum',
                'description' => 'Jumlah minimum gambar dalam artikel',
                'group' => 'media',
                'type' => 'integer',
                'value' => '2',
                'default_value' => '2',
                'unit' => 'gambar',
                'sort_order' => 60,
            ],
            [
                'key' => 'image_ideal_count',
                'label' => 'Gambar - Jumlah Ideal',
                'description' => 'Jumlah ideal gambar',
                'group' => 'media',
                'type' => 'integer',
                'value' => '3',
                'default_value' => '3',
                'unit' => 'gambar',
                'sort_order' => 61,
            ],
            [
                'key' => 'image_require_alt',
                'label' => 'Gambar - Wajib ALT Text',
                'description' => 'Setiap gambar harus memiliki ALT text',
                'group' => 'media',
                'type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'unit' => null,
                'sort_order' => 62,
            ],

            // ── FAQ ─────────────────────────────────
            [
                'key' => 'faq_min_questions',
                'label' => 'FAQ - Pertanyaan Minimum',
                'description' => 'Jumlah minimum pertanyaan FAQ. Penting untuk AI overview & rich snippet.',
                'group' => 'faq',
                'type' => 'integer',
                'value' => '4',
                'default_value' => '4',
                'unit' => 'pertanyaan',
                'sort_order' => 70,
            ],
            [
                'key' => 'faq_ideal_questions',
                'label' => 'FAQ - Pertanyaan Ideal',
                'description' => 'Jumlah ideal pertanyaan FAQ',
                'group' => 'faq',
                'type' => 'integer',
                'value' => '5',
                'default_value' => '5',
                'unit' => 'pertanyaan',
                'sort_order' => 71,
            ],

            // ── Schema Markup ─────────────────────────────────
            [
                'key' => 'schema_article',
                'label' => 'Schema - Article Markup',
                'description' => 'Gunakan Article schema markup',
                'group' => 'structure',
                'type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'unit' => null,
                'sort_order' => 80,
            ],
            [
                'key' => 'schema_faq',
                'label' => 'Schema - FAQ Markup',
                'description' => 'Gunakan FAQ schema markup untuk meningkatkan peluang tampil di Google AI overview & featured snippet',
                'group' => 'structure',
                'type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'unit' => null,
                'sort_order' => 81,
            ],

            // ── CTA ─────────────────────────────────
            [
                'key' => 'require_cta',
                'label' => 'CTA - Wajib Call To Action',
                'description' => 'Artikel harus memiliki CTA (Call to Action)',
                'group' => 'content',
                'type' => 'boolean',
                'value' => 'true',
                'default_value' => 'true',
                'unit' => null,
                'sort_order' => 90,
            ],
            [
                'key' => 'default_cta_text',
                'label' => 'CTA - Teks Default',
                'description' => 'Teks CTA default yang digunakan saat generate konten',
                'group' => 'content',
                'type' => 'text',
                'value' => 'Jika Anda ingin mengetahui lebih lanjut, Anda dapat berkonsultasi dengan tim InDepth Mental Wellness melalui WhatsApp berikut.',
                'default_value' => 'Jika Anda ingin mengetahui lebih lanjut, Anda dapat berkonsultasi dengan tim InDepth Mental Wellness melalui WhatsApp berikut.',
                'unit' => null,
                'sort_order' => 91,
            ],

            // ── Kata Terlarang ─────────────────────────────────
            [
                'key' => 'forbidden_words',
                'label' => 'Kata-Kata Terlarang',
                'description' => 'Kata-kata yang harus dihindari dalam artikel blog. Pisahkan dengan koma. Contoh: menyembuhkan, obat ajaib, pasti sembuh',
                'group' => 'content',
                'type' => 'text',
                'value' => 'menyembuhkan, obat ajaib, pasti sembuh, dijamin sembuh, 100% sembuh, tanpa efek samping, terbukti klinis, satu-satunya cara, pengganti obat, rahasia, trik curang, cara instan, cuma Anda yang tahu, viral, bikin kaya, gratis selamanya, dijamin sukses, tidak perlu usaha, menurut AI, chatGPT bilang, berdasarkan model bahasa, bunuh diri, gila, stress berat',
                'default_value' => 'menyembuhkan, obat ajaib, pasti sembuh, dijamin sembuh, 100% sembuh, tanpa efek samping, terbukti klinis, satu-satunya cara, pengganti obat, rahasia, trik curang, cara instan, cuma Anda yang tahu, viral, bikin kaya, gratis selamanya, dijamin sukses, tidak perlu usaha, menurut AI, chatGPT bilang, berdasarkan model bahasa, bunuh diri, gila, stress berat',
                'unit' => null,
                'sort_order' => 92,
            ],
        ];

        foreach ($settings as $setting) {
            SeoSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
